# Update to your own settings for URL/title
baseURL: https://flagrant.garden/
title: Flagrant Garden

module:
  # Dev use only! Do not uncomment unless you're modifying a theme module!
  # Only used in local testing; make sure to override the path to your own local copy
  # replacements: 'github.com/platenio/hugo-platen -> C:\code\platen\themes\platen'
  # replacements: 'github.com/platenio/hugo-platen-netlify -> C:\code\platen\hugo-platen-netlify'
  imports:
    - path: github.com/platenio/platen/modules/platen

disablePathToLower: true
enableGitInfo: true

# Needed for mermaid/katex shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
  tableOfContents:
    startLevel: 1
    endLevel: 4

# Multi-lingual mode config
# There are different options to translate files
# See https://gohugo.io/content-management/multilingual/#translation-by-filename
# And https://gohugo.io/content-management/multilingual/#translation-by-content-directory
languages:
  en:
    languageName: English
    contentDir: content
    weight: 1

menu:
  after:
    - name: Available Cultivars
      url: /cultivars
      weight: 10
    - name: Friendly Horticulturists
      url: /horticulturists
      weight: 20
  before:
    - name: "Cultivate Flagrantly"
      url: "/cultivation"
      weight: 10
    - name: Posts
      url: /posts
      weight: 20
