# yaml-language-server: $schema=http://json-schema.org/draft-07/schema
$comment: https://gohugo.io/templates/internal/#open-graph
$schema: http://json-schema.org/draft-07/schema
$id: https://platen.io/schemas/hugo/config/params/sharing.json
title: Site Parameters for hugo's sharing integrations
description: >-
  Hugo supports configuring defaults for both Open Graph and Twitter Cards
  with site parameters.
type: object
properties:
  description:
    $id: "#/description"
    title: Site Description
    description: >-
      Specify a one to two sentence string to display as a synopsis for your
      site when shared. This is used by both Open Graph and Twitter Cards.
    type: string
    default: ""
  images:
    $id: "#/images"
    title: Site Image
    description: >-
      Specify one or more site-relative links to images to display for your
      site when shared. This is used by both Open Graph and Twitter Cards.
      The first image is used on the card, but extra images are included in
      the metadata.
    type: array
    items:
      type: string
    uniqueItems: true
    minItems: 1
    maxItems: 6
  title:
    $id: "#/title"
    title: Site Title
    description: >-
      Specify a string to display as the title for your site when shared. If
      this value isn't specified, the top level **title** in your site
      configuration is used instead.
    type: string
    default: ""
